"""Add year_of_study to Registration model

Revision ID: 5c44f8cc4a00
Revises: dadedddbfedf
Create Date: 2025-05-02 00:08:31.487179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c44f8cc4a00'
down_revision = 'dadedddbfedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('year_of_study')

    # ### end Alembic commands ###
